# sudo false implies containerized builds
sudo: false
language: python
python:
  - 3.6
install: 
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - pip install .
script:
  - simply_domain.py -h

  
