# sudo false implies containerized builds
sudo: ture
language: python
python:
  - 3.6
install: 
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - pip install .
script:
  - python3 simplydomain.py -h

  
