# sudo false implies containerized builds
sudo: ture
language: python
python:
  - 3.6
install: 
  - pip install nose
  - pip install coverage
  - pip install coveralls
script:
  - git clone https://github.com/SimplySecurity/SimplyDomain.git
  - cd SimplyDomain/setup/
  - pip install -r requirements.txt
  - cd ..
  - python3 SimplyDomain.py -h
  - nosetests --with-coverage
after_success:
   - coveralls
  
